name: fireblend_stream_provider
description: A convenient and cost-effective way of retrieving a Stream from Firebase Realtime Database, using the fireblend library.
# version: 1.0.0
# author: Eduardo <email@example.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.22.6
  fireblend:
    git:
      url: https://github.com/darter/fireblend
      path: fireblend/

dev_dependencies:
  test: ^1.9.4
  analyzer: 0.39.1 # TODO: Remove when the issue is fixed.
  # https://github.com/dart-lang/sdk/issues/39702
