name: fireblend_stream_provider
description: A convenient and cost-effective way of retrieving a Stream from Firebase Realtime Database, using the fireblend library.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  rxdart: 0.22.6
  fireblend:
    git:
      url: https://github.com/darter/fireblend
      path: fireblend/

dev_dependencies:
  test: 
  analyzer: 
  # https://github.com/dart-lang/sdk/issues/39702
