name: fireblend_stream_provider
description: A convenient and cost-effective way of retrieving a Stream from Firebase Realtime Database, using the fireblend library.
# version: 1.0.0
# homepage: https://www.example.com
# author: Eduardo <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.18.1
  fireblend:
    git:
      url: https://github.com/darter/fireblend
      path: fireblend/

dev_dependencies:
  test: ^1.0.0
